### PR TITLE
[Fix #203] Fix null values for every store

### LINKED ISSUE #203: Allow Sumo Riak Store to use nullable fields
Nowadays Sumo Riak Store stores ``<<"undefined">>`` for `undefined` values.
We need it to properly store `undefined` (or some internal representation of it) and to also retrieve it on wakeup.

### PR DESCRIPTION
**Pull request by harenson**
- Set SumoDB to treat string and text type fields as binary
- Switch to pattern matching instead of list length in tests

Note: after talking with @cabol  and since `Riak` doesn't have the concept of `null`, we have chosen to use `$nil` as a reserved word within `SumoDB` for `Riak` **null** values.

### CODE REVIEW

File: test/conditional_logic_SUITE.erl [hunk 1]
```diff
@@ -44,11 +44,11 @@ init_per_suite(Config) ->
...
-        sumo:persist(Module, Module:new("Jane", "Doe")),
-        sumo:persist(Module, Module:new("John", "Doe", 30)),
-        sumo:persist(Module, Module:new("Jane Jr.", "Doe", 5)),
-        sumo:persist(Module, Module:new("Joe", "Armstrong")),
-        sumo:persist(Module, Module:new("Alan", "Turing", 102, "Computer St.")),
+        sumo:persist(Module, Module:new(<<"Jane">>, <<"Doe">>)),
+        sumo:persist(Module, Module:new(<<"John">>, <<"Doe">>, 30)),
+        sumo:persist(Module, Module:new(<<"Jane Jr.">>, <<"Doe">>, 5)),
+        sumo:persist(Module, Module:new(<<"Joe">>, <<"Armstrong">>)),
+        sumo:persist(Module, Module:new(<<"Alan">>, <<"Turing">>, 102, <<"Computer St.">>)),
```
Comment (gadgetci) [inline test/conditional_logic_SUITE.erl]: According to **Elvis**:
> Line 51 is too long:         sumo:persist(Module, Module:new(<<"Alan">>, <<"Turing">>, 102, <<"Computer St.">>)),.

File: test/sumo_basic_SUITE.erl [hunk 2]
```diff
@@ -112,32 +112,32 @@ find_module(Module) ->
...
-  0.0 = Module:height(First),
-  <<>> = Module:description(First),
+  undefined = Module:height(First),
+  undefined = Module:description(First),
   {Today, _} = Module:created_at(First),
   % Check that it returns what we have inserted
-  [LastPerson | _NothingElse] = sumo:find_by(Module, [{last_name, "LastName"}]),
-  "Name" = Module:name(LastPerson),
-  "LastName" = Module:last_name(LastPerson),
+  [LastPerson | _NothingElse] = sumo:find_by(Module, [{last_name, <<"LastName">>}]),
```
Comment (gadgetci) [inline test/sumo_basic_SUITE.erl]: According to **Elvis**:
> Line 136 is too long:   [LastPerson | _NothingElse] = sumo:find_by(Module, [{last_name, <<"LastName">>}]),.
