### PR TITLE
[Fix #211] Add meta testing and Fix dialyzer warnings

### LINKED ISSUE #211: Add Meta Testing
Add a test suite based on `ktn_meta_SUITE`

### PR DESCRIPTION
**Pull request by harenson**

### CODE REVIEW

File: test/sumo_test_people.erl [hunk 1]
```diff
@@ -56,7 +71,7 @@ sumo_sleep(Person) ->
     description => Person#person.description,
     profile_image => Person#person.profile_image}.
 
--spec sumo_wakeup(sumo:doc()) -> person().
+-spec sumo_wakeup(Person::sumo:doc()) -> sumo:user_doc().
```
Comment (elbrujohalcon) [inline test/sumo_test_people.erl]: This is not correct, the result of `sumo_wakeup` (like the input of `sumo_sleep`) should be `person()`.

File: test/riak/sumo_test_purchase_order.erl [hunk 2]
```diff
@@ -52,9 +52,9 @@ sumo_schema() ->
     , sumo:new_field(created_at, datetime, [not_null])
     , sumo:new_field(order_num,  binary,   [not_null])
     , sumo:new_field(po_date,    datetime, [not_null])
-    , sumo:new_field(ship_to,    address,  [not_null])
-    , sumo:new_field(bill_to,    address,  [not_null])
-    , sumo:new_field(items,      items,    [not_null])
+    , sumo:new_field(ship_to,    binary,  [not_null])
```
Comment (elbrujohalcon) [inline test/riak/sumo_test_purchase_order.erl]: please realign the `[not_null]`s
